# Generated by Django 5.2.14 on 2026-05-26 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.CreateModel(
            name='WorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
            ],
            options={
                'db_table': 'tm_worship_session',
            },
        ),
        
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('member_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('moved', 'Moved')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tm_member',
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langfuse_threadid', models.CharField(blank=True, max_length=100, null=True)),
                ('conversation_title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_aiconversation',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('visit_count', models.IntegerField(default=0)),
                ('first_visit', models.DateField(blank=True, null=True)),
                ('last_visit', models.DateField(blank=True, null=True)),
                ('face_image', models.BinaryField(blank=True, null=True)),
                ('face_encoding', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_to_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.member')),
            ],
            options={
                'db_table': 't_guest',
            },
        ),
        migrations.CreateModel(
            name='FollowupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_followup', models.CharField(choices=[('new', 'New'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('followup_type', models.CharField(choices=[('call', 'Call'), ('visited', 'Visited')], max_length=20, null=True)),
                ('followup_date', models.DateField()),
                ('result_followup', models.CharField(max_length=255, null=True)),
                ('explain_followup', models.TextField(blank=True, null=True)),
                ('progress_followup', models.CharField(choices=[('not_yet', 'Not Yet'), ('followed_up', 'Followed up'), ('need_more', 'Need More Follow Up'), ('completed', 'Completed')], default='not_yet', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='attendance.member')),
            ],
            options={
                'db_table': 'tm_followup_members',
                'ordering': ['-followup_date'],
            },
        ),
        migrations.CreateModel(
            name='MemberFaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.JSONField()),
                ('face_image', models.BinaryField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.member')),
            ],
            options={
                'db_table': 't_member_face_embedding',
            },
        ),
        migrations.CreateModel(
            name='SummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_start_date', models.DateField(blank=True, null=True)),
                ('report_end_date', models.DateField(blank=True, null=True)),
                ('total_members', models.IntegerField(default=0)),
                ('total_guests', models.IntegerField(default=0)),
                ('total_attendance', models.IntegerField(default=0)),
                ('report_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_summary_report',
                'ordering': ['-created_at'],
                'unique_together': {('report_start_date', 'report_end_date')},
            },
        ),
        migrations.CreateModel(
            name='TimelineDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_time', models.DateTimeField()),
                ('face_image', models.BinaryField(blank=True, null=True)),
                ('face_encoding', models.JSONField(blank=True, null=True)),
                ('detection_status', models.CharField(choices=[('know', 'Know'), ('ambiguous', 'Ambiguous'), ('unknown', 'Unknown')], max_length=50)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('guest_confirmed', 'Guest Confirmed')], default='pending', max_length=50)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.guest')),
                ('final_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_validations', to='attendance.member')),
                ('matched_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_matches', to='attendance.member')),
            ],
            options={
                'db_table': 't_timlinedata_record',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin / Church Committee'), ('leader', 'Church Leader (Pastor)')], default='admin', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_user_role',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(blank=True, null=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.guest')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.member')),
                ('facedetection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.timelinedatarecord')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.worshipsession')),
            ],
            options={
                'db_table': 't_attendance',
            },
        ),
    ]
