# Generated by Django 5.2.14 on 2026-05-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='from_where',
            field=models.TextField(blank=True, null=True),
        ),
    ]
