# Generated by Django 5.2.5 on 2026-03-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_alter_userprofile_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SummaryReport",
        )
    ]