# Generated by Django 6.0.4 on 2026-05-25 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_delete_summaryreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberfaceembedding',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='memberfaceembedding',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='timelinedatarecord',
            name='image_path',
        ),
        migrations.AddField(
            model_name='guest',
            name='face_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberfaceembedding',
            name='face_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelinedatarecord',
            name='face_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberfaceembedding',
            name='face_encoding',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='timelinedatarecord',
            name='detection_status',
            field=models.CharField(choices=[('know', 'Know'), ('ambiguous', 'Ambiguous'), ('unknown', 'Unknown')], max_length=50),
        ),
        migrations.AlterField(
            model_name='timelinedatarecord',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FollowupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_followup', models.CharField(choices=[('new', 'New'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('followup_type', models.CharField(choices=[('call', 'Call'), ('visited', 'Visited')], max_length=20, null=True)),
                ('followup_date', models.DateField()),
                ('result_followup', models.CharField(max_length=255, null=True)),
                ('explain_followup', models.TextField(blank=True, null=True)),
                ('progress_followup', models.CharField(choices=[('not_yet', 'Not Yet'), ('followed_up', 'Followed up'), ('need_more', 'Need More Follow Up'), ('completed', 'Completed')], default='not_yet', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='attendance.member')),
            ],
            options={
                'db_table': 'tm_followup_members',
                'ordering': ['-followup_date'],
            },
        ),
        migrations.CreateModel(
            name='SummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_start_date', models.DateField()),
                ('report_end_date', models.DateField()),
                ('total_members', models.IntegerField(default=0)),
                ('total_guests', models.IntegerField(default=0)),
                ('total_attendance', models.IntegerField(default=0)),
                ('report_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_summary_report',
                'ordering': ['-created_at'],
                'unique_together': {('report_start_date', 'report_end_date')},
            },
        ),
    ]
